name: Convert Python to EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'  # Zvoľ verziu Pythonu

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Convert to EXE
      run: |
        pyinstaller --onefile --clean PET_LEVEL4.py
        ls dist  # Zobraz obsah adresára dist

    - name: List files in dist directory
      run: |
        ls dist  # Zobraz obsah adresára dist

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/PET_LEVEL4.exe  # Uprav názov, ak sa vytvára iný súbor
